name: Caller Workflow

on:
  push:
      
jobs:
  call-workflow-in-another-repo:
    - name: echo
      run: echo hello world
    - name: call reusable workflow
      uses: outsideris/actions-test/.github/workflows/called.yaml@4189beb6cbbebde39af9a0a4f3f2695d165973cf
      with:
        username: testuser
      secrets:
        SECRET_SEED: REMOTE_SEED
        