name: Reusable Caller Workflow

on:
  push:
      
jobs:
  call-workflow-in-another-repo:
    uses: outsideris/actions-test/.github/workflows/called.yaml@4189beb6cbbebde39af9a0a4f3f2695d165973cf
    with:
      username: testuser
    secrets:
      SECRET_SEED: REMOTE_SEED
        