name: Continuous integration
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  env:
    CI: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: NODE_ENV
        run: echo $NODE_ENV
      - name: lint
        run: npm run lint
