name: Trigger repository_dispatch
on: workflow_dispatch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: gh api /repos/outsideris/actions-test/dispatches -f event_type='demo_event'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
